### ISSUE TITLE
exec /usr/bin/caddy: operation not permitted

### ISSUE THREAD

**Issue by pingiun** [caddyserver/gateway#7]
I get the error `exec /usr/bin/caddy: operation not permitted` when the securityContext is defined. I disabled the securityContext for the caddy container, which worked. But this required lowering the security policy for the caddy-system namespace

**Comment by matthewpi** [comment]
This may be resolved by <https://github.com/caddyserver/gateway/commit/7e23d859282b37591d3da6903639627c864f5a7d>.

I ran the existing container using and inspected the binary
```
~
❯ podman run -it --entrypoint /bin/ash --network=host --rm --read-only 'ghcr.io/caddyserver/gateway:caddy-2.8.4'

/srv # ls -lsAh /usr/bin/caddy
  39.2M -rwxr-xr-x    1 root     root       39.2M Jun  5 00:43 /usr/bin/caddy

/srv # getcap /usr/bin/caddy
/usr/bin/caddy cap_net_bind_service=ep
```

The proper exec permissions are set (755) but the `cap_net_bind_service` is not wanted nor necessary. In the linked commit I disabled the SETCAP option for xcaddy which should hopefully avoid this issue.

The new image has been built, if you could test it and let me know if it works, I'd appreciate it.

**Comment by pingiun** [comment]
Sorry I was trying out caddy, but ended up switching to envoy gateway in the end

**Comment by matthewpi** [comment]
All good.  Hopefully this is solved so other people don't run into this issue.

I personally run the Gateway on my cluster, but I use a different Caddy image.
